CREATE DATABASE car_db;

\c car_db;

CREATE TABLE IF NOT EXISTS car_table
(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR,
    brand VARCHAR,
    country VARCHAR,
    price INTEGER,
    horsepower INTEGER
);